const hoursFromNow = (h) => new Date(Date.now() + h * 60 * 60 * 1000);

export const buildNewArrivals = () => [
  {
    name: "इलेक्ट्रिक स्कुटर मिनी",
    slug: "electric-scooter-mini",
    description:
      "Foldable electric scooter, 25km range, 3 speed modes. लन्च अफर आज मात्र!",
    image: "https://images.unsplash.com/photo-1604868189265-219ba7ffc595?w=600",
    category: "Electronics",
    priceCents: 899900,
    originalPriceCents: 1299900,
    urgencyBadge: "🚀 लन्च अफर आज मात्र!",
    saleEndsAt: hoursFromNow(8),
    stockCount: 20,
    rating: 4.6,
    reviewCount: 41,
    section: "new-arrivals",
    intendedDarkPatterns: ["false_urgency"],
  },
  {
    name: "हस्तनिर्मित पश्मिना जुत्ता",
    slug: "handmade-pashmina-slippers",
    description:
      "Wool-felted slippers, hand-stitched in Kathmandu. स्टकमा ३ जोडा मात्र बाँकी!",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600",
    category: "Fashion",
    priceCents: 99900,
    stockCount: 3,
    lowStockBadge: "स्टकमा ३ जोडा मात्र!",
    rating: 4.8,
    reviewCount: 29,
    section: "new-arrivals",
    intendedDarkPatterns: ["scarcity"],
  },
  {
    name: "Copper Water Bottle Set",
    slug: "copper-water-bottle-set",
    description:
      "Ayurvedic copper bottles, 1L each. Trending -- 76 sold in the last 24 hours.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600",
    category: "Home",
    priceCents: 149900,
    rating: 4.7,
    reviewCount: 512,
    purchasesLast24h: 76,
    stockCount: 60,
    section: "new-arrivals",
    intendedDarkPatterns: ["social_proof"],
  },
  {
    name: "अनुहार सिरम सेट",
    slug: "face-serum-set",
    description:
      "Vitamin C + Niacinamide serum duo. मूल्य हेर्न खाता आवश्यक छ।",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600",
    category: "Beauty",
    priceCents: 179900,
    requiresAccountToViewPrice: true,
    forcedNewsletterOptIn: true,
    stockCount: 40,
    rating: 4.5,
    reviewCount: 88,
    section: "new-arrivals",
    intendedDarkPatterns: ["forced_action"],
  },
  {
    name: "Home Cleaning Subscription Box",
    slug: "home-cleaning-subscription-box",
    description:
      "Monthly eco-friendly cleaning supplies delivered to your door.",
    image: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=600",
    category: "Subscription",
    priceCents: 89900,
    isSubscription: true,
    obstructedCancellation: true,
    obstructionNote:
      "To cancel, email support and allow up to 10 business days for a callback " +
      "to confirm your cancellation request before it takes effect.",
    rating: 4.0,
    reviewCount: 34,
    section: "new-arrivals",
    intendedDarkPatterns: ["obstruction"],
  },
  {
    name: "क्यामेरा ट्राइपड किट",
    slug: "camera-tripod-kit",
    description: "Adjustable aluminium tripod with phone and camera mounts.",
    image: "https://images.unsplash.com/photo-1616423640778-28d1b53229bd?w=600",
    category: "Electronics",
    priceCents: 129900,
    hiddenFeeCents: 19900,
    hiddenFeeLabel: "अनिवार्य ह्यान्डलिङ शुल्क",
    preCheckedAddon: {
      enabled: true,
      name: "विस्तारित वारेन्टी",
      priceCents: 24900,
    },
    stockCount: 50,
    rating: 4.4,
    reviewCount: 77,
    section: "new-arrivals",
    intendedDarkPatterns: ["sneaking"],
  },
  {
    name: "Wireless Mechanical Keyboard",
    slug: "wireless-mechanical-keyboard",
    description: "Hot-swappable mechanical keyboard with per-key RGB.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600",
    category: "Electronics",
    priceCents: 349900,
    declineButtonText: "No thanks, I prefer a worse typing experience",
    stockCount: 45,
    rating: 4.8,
    reviewCount: 233,
    section: "new-arrivals",
    intendedDarkPatterns: ["confirmshaming"],
  },
  {
    name: "मौसमी फलफूल बास्केट",
    slug: "seasonal-fruit-basket",
    description: "Hand-picked seasonal fruits, delivered fresh weekly.",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600",
    category: "Home",
    priceCents: 59900,
    stockCount: 90,
    rating: 4.6,
    reviewCount: 51,
    section: "new-arrivals",
    intendedDarkPatterns: [],
  },
  {
    name: "Handloom Cotton Bedsheet",
    slug: "handloom-cotton-bedsheet",
    description: "Queen-size handloom cotton bedsheet with 2 pillow covers.",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600",
    category: "Home",
    priceCents: 189900,
    stockCount: 70,
    rating: 4.5,
    reviewCount: 39,
    section: "new-arrivals",
    intendedDarkPatterns: [],
  },
];
